package com.dov4k1n.grammarforces.util.verbs

class PastSimple {
    fun conjugate(verb: String, pronoun: String): String {
        if (verb == "be") {
            return when (pronoun) {
                "I", "he", "she", "it" -> "was"
                "you", "we", "they" -> "were"
                else -> "err: unknown pronoun"
            }
        }

        val irregular = getIrregularVerbs().find { it.infinitive == verb }

        return when {
            irregular != null -> irregular.pastSimple
            else -> verb + "ed"
        }
    }
}

data class IrregularVerb(
    val infinitive: String,
    val pastSimple: String,
    val pastParticiple: String
)

private fun getIrregularVerbs(): Set<IrregularVerb> {
    return setOf(
        IrregularVerb("abide", "abode", "abode"),
        IrregularVerb("arise", "arose", "arisen"),
        IrregularVerb("awake", "awoke", "awoken"),
        IrregularVerb("be", "was, were", "been"),
        IrregularVerb("bear", "bore", "borne / born"),
        IrregularVerb("beat", "beat", "beaten"),
        IrregularVerb("become", "became", "become"),
        IrregularVerb("beget", "begat / begot", "begotten"),
        IrregularVerb("begin", "began", "begun"),
        IrregularVerb("bend", "bent", "bent"),
        IrregularVerb("bereave", "bereft / bereaved", "bereft / bereaved"),
        IrregularVerb("bet", "bet", "bet"),
        IrregularVerb("bid", "bid / bade", "bid / bidden"),
        IrregularVerb("bleed", "bled", "bled"),
        IrregularVerb("blow", "blew", "blown"),
        IrregularVerb("break", "broke", "broken"),
        IrregularVerb("breed", "bred", "bred"),
        IrregularVerb("bring", "brought", "brought"),
        IrregularVerb("broadcast", "broadcast", "broadcast"),
        IrregularVerb("build", "built", "built"),
        IrregularVerb("burn", "burnt / burned", "burnt / burned"),
        IrregularVerb("burst", "burst", "burst"),
        IrregularVerb("buy", "bought", "bought"),
        IrregularVerb("can", "could", "could"),
        IrregularVerb("cast", "cast", "cast"),
        IrregularVerb("catch", "caught", "caught"),
        IrregularVerb("chide", "chid", "chiden"),
        IrregularVerb("choose", "chose", "chosen"),
        IrregularVerb("cling", "clung", "clung"),
        IrregularVerb("clothe", "clad / clothed", "clad / clothed"),
        IrregularVerb("come", "came", "come"),
        IrregularVerb("cost", "cost", "cost"),
        IrregularVerb("creep", "crept", "crept"),
        IrregularVerb("cut", "cut", "cut"),
        IrregularVerb("deal", "dealt", "dealt"),
        IrregularVerb("dig", "dug", "dug"),
        IrregularVerb("dive", "dived", "dived / dove"),
        IrregularVerb("do", "did", "done"),
        IrregularVerb("draw", "drew", "drawn"),
        IrregularVerb("dream", "dreamt / dreamed", "dreamt / dreamed"),
        IrregularVerb("drink", "drank", "drunk"),
        IrregularVerb("drive", "drove", "driven"),
        IrregularVerb("dwell", "dwelt", "dwelt / dwelled"),
        IrregularVerb("eat", "ate", "eaten"),
        IrregularVerb("fall", "fell", "fallen"),
        IrregularVerb("feed", "fed", "fed"),
        IrregularVerb("feel", "felt", "felt"),
        IrregularVerb("fight", "fought", "fought"),
        IrregularVerb("find", "found", "found"),
        IrregularVerb("flee", "fled", "fled"),
        IrregularVerb("fling", "flung", "flung"),
        IrregularVerb("fly", "flew", "flown"),
        IrregularVerb("forbid", "forbade", "forbidden"),
        IrregularVerb("forecast", "forecast", "forecast"),
        IrregularVerb("forget", "forgot", "forgotten / forgot"),
        IrregularVerb("forgive", "forgave", "forgiven"),
        IrregularVerb("forsake", "forsook", "forsaken"),
        IrregularVerb("forsee", "foresaw", "foresawn"),
        IrregularVerb("freeze", "froze", "frozen"),
        IrregularVerb("get", "got", "gotten / got"),
        IrregularVerb("give", "gave", "given"),
        IrregularVerb("go", "went", "gone"),
        IrregularVerb("grind", "ground", "ground"),
        IrregularVerb("grow", "grew", "grown"),
        IrregularVerb("hang", "hung", "hung"),
        IrregularVerb("have", "had", "had"),
        IrregularVerb("hear", "heard", "heard"),
        IrregularVerb("hide", "hid", "hidden"),
        IrregularVerb("hit", "hit", "hit"),
        IrregularVerb("hold", "held", "held"),
        IrregularVerb("hurt", "hurt", "hurt"),
        IrregularVerb("keep", "kept", "kept"),
        IrregularVerb("kneel", "knelt / knelled", "knelt / kneeled"),
        IrregularVerb("know", "knew", "known"),
        IrregularVerb("lay", "laid", "laid"),
        IrregularVerb("lead", "led", "led"),
        IrregularVerb("lean", "leant / leaned", "leant / leaned"),
        IrregularVerb("leap", "leapt / leaped", "leapt / leaped"),
        IrregularVerb("learn", "learnt", "learnt"),
        IrregularVerb("leave", "left", "left"),
        IrregularVerb("lend", "lent", "lent"),
        IrregularVerb("let", "let", "let"),
        IrregularVerb("lie", "lay", "lain"),
        IrregularVerb("light", "lit / lighted", "lit / lighted"),
        IrregularVerb("lose", "lost", "lost"),
        IrregularVerb("make", "made", "made"),
        IrregularVerb("mean", "meant", "meant"),
        IrregularVerb("meet", "met", "met"),
        IrregularVerb("mow", "mowed", "mowed / mown"),
        IrregularVerb("offset", "offset", "offset"),
        IrregularVerb("overcome", "overcame", "overcome"),
        IrregularVerb("partake", "partook", "partaken"),
        IrregularVerb("pay", "paid", "paid"),
        IrregularVerb("plead", "pled / pleaded", "pled / pleaded"),
        IrregularVerb("preset", "preset", "preset"),
        IrregularVerb("prove", "proved", "proven / proved"),
        IrregularVerb("put", "put", "put"),
        IrregularVerb("quit", "quit", "quit"),
        IrregularVerb("read", "read", "read"),
        IrregularVerb("relay", "relaid", "relaid"),
        IrregularVerb("rend", "rent", "rent"),
        IrregularVerb("rid", "rid", "rid"),
        IrregularVerb("ride", "rode", "ridden"),
        IrregularVerb("ring", "rang", "rung"),
        IrregularVerb("rise", "rose", "risen"),
        IrregularVerb("run", "ran", "run"),
        IrregularVerb("saw", "saw / sawed", "sawn / sawed"),
        IrregularVerb("say", "said", "said"),
        IrregularVerb("see", "saw", "seen"),
        IrregularVerb("seek", "sought", "sought"),
        IrregularVerb("sell", "sold", "sold"),
        IrregularVerb("send", "sent", "sent"),
        IrregularVerb("set", "set", "set"),
        IrregularVerb("shake", "shook", "shaken"),
        IrregularVerb("shed", "shed", "shed"),
        IrregularVerb("shine", "shone", "shone"),
        IrregularVerb("shoe", "shod", "shod"),
        IrregularVerb("shoot", "shot", "shot"),
        IrregularVerb("show", "showed", "shown"),
        IrregularVerb("shut", "shut", "shut"),
        IrregularVerb("sing", "sang", "sung"),
        IrregularVerb("sink", "sank / sunk", "sunk / sunken"),
        IrregularVerb("sit", "sat", "sat"),
        IrregularVerb("slay", "slew", "slain"),
        IrregularVerb("sleep", "slept", "slept"),
        IrregularVerb("slide", "slid", "slid"),
        IrregularVerb("slink", "slunk / slinked", "slunk / slinked"),
        IrregularVerb("slit", "slit", "slit"),
        IrregularVerb("smell", "smelt", "smelt"),
        IrregularVerb("sow", "sowed", "sown / sowed"),
        IrregularVerb("speak", "spoke", "spoken"),
        IrregularVerb("speed", "sped", "sped"),
        IrregularVerb("spell", "spelt", "spelt"),
        IrregularVerb("spend", "spent", "spent"),
        IrregularVerb("spill", "spilt / spilled", "spilt / spilled"),
        IrregularVerb("spin", "spun", "spun"),
        IrregularVerb("spit", "spat / spit", "spat / spit"),
        IrregularVerb("split", "split", "split"),
        IrregularVerb("spoil", "spoilt", "spoilt"),
        IrregularVerb("spread", "spread", "spread"),
        IrregularVerb("spring", "sprang", "sprung"),
        IrregularVerb("stand", "stood", "stood"),
        IrregularVerb("steal", "stole", "stolen"),
        IrregularVerb("stick", "stuck", "stuck"),
        IrregularVerb("sting", "stung", "stung"),
        IrregularVerb("stink", "stank", "stunk"),
        IrregularVerb("strew", "strewed", "strewn / strewed"),
        IrregularVerb("strike", "struck", "stricken / struck"),
        IrregularVerb("strive", "strove", "striven"),
        IrregularVerb("swear", "swore", "sworn"),
        IrregularVerb("sweat", "sweat / sweated", "sweat / sweated"),
        IrregularVerb("sweep", "swept", "swept"),
        IrregularVerb("swell", "swelled", "swollen / swelled"),
        IrregularVerb("swim", "swam", "swum"),
        IrregularVerb("swing", "swung", "swung"),
        IrregularVerb("take", "took", "taken"),
        IrregularVerb("teach", "taught", "taught"),
        IrregularVerb("tear", "tore", "torn"),
        IrregularVerb("tell", "told", "told"),
        IrregularVerb("think", "thought", "thought"),
        IrregularVerb("thrive", "throve / thrived", "thriven / thrived"),
        IrregularVerb("throw", "threw", "thrown"),
        IrregularVerb("thrust", "thrust", "thrust"),
        IrregularVerb("tread", "trod", "trodden"),
        IrregularVerb("typeset", "typeset", "typeset"),
        IrregularVerb("undergo", "underwent", "undergone"),
        IrregularVerb("understand", "understood", "understood"),
        IrregularVerb("wake", "woke", "woken"),
        IrregularVerb("wear", "wore", "worn"),
        IrregularVerb("weep", "wept", "wept"),
        IrregularVerb("wet", "wet / wetted", "wet / wetted"),
        IrregularVerb("win", "won", "won"),
        IrregularVerb("wind", "wound", "wound"),
        IrregularVerb("withdraw", "withdrew", "withdrawn"),
        IrregularVerb("wring", "wrung", "wrung"),
        IrregularVerb("write", "wrote", "written")
    )
}